### ISSUE TITLE
Prototype Release is source code

### ISSUE THREAD

**Issue by lucidbard** [somir1/AqueductMain#1]
Releases should be binary or installable for the target platform.

**Comment by somir1** [comment]
Oh ok we are just having some issues setting it up

**Comment by lucidbard** [comment]
Feel free to bring them up in webcourses, others may have similar issues. I'm around

**Comment by jose34953** [comment]
I made another one is that the correct way to do it?

**Comment by lucidbard** [comment]
You should zip the entire directory that results -- in this case, the exe depends on a unity player dll file.

**Comment by lucidbard** [comment]
![image](https://user-images.githubusercontent.com/2390806/45395573-c372b880-b604-11e8-8762-7e0c4f1a8f20.png)

**Comment by lucidbard** [comment]
It still requires an "Aqueduct_Data" folder that has assets it depends on.

**Comment by jose34953** [comment]
It gives me an error when I try to compress the repository File not found or no read permission

**Comment by lucidbard** [comment]
Hmm -- try posting a screenshot

**Comment by jose34953** [comment]
<img width="960" alt="error" src="https://user-images.githubusercontent.com/33074171/45396182-f2d6f480-b607-11e8-9eef-5da528bcf49b.png">

**Comment by lucidbard** [comment]
Is that the source directory, or a build directory? You can't compress a source directory while its open in Unity.

**Comment by jose34953** [comment]
It's the source I closed Unity and compressed it, but it is too big to add to the release.

**Comment by lucidbard** [comment]
Don't compress the source -- it's here in the repo. When you create a build in unity, it asks you to specify a directory. The only directory you need to compress is that one -- not the source repository. It should be smaller by far. https://docs.unity3d.com/Manual/PublishingBuilds.html

**Comment by jose34953** [comment]
I compressed Aqueduct it has the exe the dll and aqueduct_data and its still too big

**Comment by lucidbard** [comment]
Ok -- have you tried uploading to the student server, or is it still too big?

**Comment by jose34953** [comment]
I think I figured it out and released it.

**Comment by lucidbard** [comment]
Looks like progress. Some release notes may be handy (how to play, buttons, known bugs)
